"""Simulate a dungeon crawler with procedurally generated rooms, combat, and loot collection"""
"test commit 5/1/26 4:50pm"
import data
import random
import time 


class Character:
    """
    Base character parent class, used for inheritence of all character types
    Attributes:
        health (int) the health of the character
    """
    def __init__(self, health):
        self.health = health
    
    
    def choose_move(self, player):
        """
        function to select the computers move based on player and own health
        Args:
            player (Player) the human player
        Returns:
            (str) the move generated by the algorithm
        """
        
        choices = {
            'Attack': 0,
            'Heal': 0,
            'Defend': 0     
        }
        
        for move in choices: 
            
            if move == 'Attack':
                #player low and enemy high 
                if 40 >= player.health and self.health >= 70:
                    choices[move]+=90 
                #player low and enemy medium 
                elif 40 >= player.health and 40 >= self.health < 70:
                    choices[move]+=70
                # both medium 
                elif 40 < player.health < 70 and 40 >= self.health < 70:
                    choices[move] += 50
                # both low 
                elif 40 > player.health and 40 > self.health:
                    choices[move] += 45
                # player med and enemy low 
                elif 40 < player.health < 70 and self.health < 40:
                    choices[move] += 20
                #player high and enemy low
                elif player.health > 70 and self.health < 40:
                    choices[move] += 10
                    
            if move == "Defend":
                #player low and enemy high 
                if 40 >= player.health and self.health >= 70:
                    choices[move]+=35
                #player low and enemy medium 
                elif 40 >= player.health and 40 >= self.health < 70:
                    choices[move]+=70
                # both medium 
                elif 40 < player.health < 70 and 40 >= self.health < 70:
                    choices[move] += 40
                # both low 
                elif 40 > player.health and 40 > self.health:
                    choices[move] += 30
                # player med and enemy low 
                elif 40 < player.health < 70 and self.health < 40:
                    choices[move] += 10
                #player high and enemy low
                elif player.health > 70 and self.health < 40:
                    choices[move] += 0
            
            if move == "Heal":
                if self.potion_count > 0: 
                    #player low and enemy high 
                    if 40 >= player.health and self.health >= 70:
                        choices[move]+=10
                    #player low and enemy medium 
                    elif 40 >= player.health and 40 >= self.health < 70:
                        choices[move]+=25
                    # both medium 
                    elif 40 < player.health < 70 and 40 >= self.health < 70:
                        choices[move] += 40
                    # both low 
                    elif 40 > player.health and 40 > self.health:
                        choices[move] += 50
                    # player med and enemy low 
                    elif 40 < player.health < 70 and self.health < 40:
                        choices[move] += 75
                    #player high and enemy low
                    elif player.health > 70 and self.health < 40:
                        choices[move] += 90
                else: 
                    choices[move] = 0
                     
        sorted_moves = sorted(choices.items(), key=lambda m: m[1], reverse=True)
        return sorted_moves[0][0]


class Player(Character):
    """
    Class for the player character
    Attributes:
        max_health(int) the maximum health for the character
        character_class (str) the class (mage, warrior, thief) of the player
        player_name (str) the name of the player, selected by user
        row_pos (int) the row of the 4x4 grid the player is on
        col_pos (int) the col of the 4x4 grid the player is on
        dodge_chance (int) the players chance to dodge an incoming attack
        weapon (Weapon) the players weapon, assigend based on class
        gold (int) the amount of gold the player has
        inventory (dict) the players inventory of items
        is_hero (bool) game loop variable to see if boss has been defeated
        combat_streak (bool) used to ensure a combat encounter every other turn.
    """
    def __init__(self, health, character_class, player_name, dodge_chance):
        super().__init__(health)
        self.max_health = health
        self.character_class = character_class
        self.player_name = player_name
        self.row_pos = 3
        self.col_pos = 3
        self.dodge_chance = dodge_chance
        self.weapon = None
        self.gold = 0
        self.inventory = {"Health Potion": 2}
        self.is_hero = False
        self.combat_streak = False
        
        
    def display_dungeon_map(self):
        """
        function to display dungeon map with player position
        Side Effects:
            prints the dungeon may to the console
        """
        
        map = [
        ["\u25A0\t", "\u25A0\t", "\u25A0\t","\u25A0\t"],
        ["\u25A0\t", "\u25A0\t", "\u25A0\t", "\u25A0\t"],
        ["\u25A0\t", "\u25A0\t", "\u25A0\t", "\u25A0\t"],
        ["\u25A0\t", "\u25A0\t", "\u25A0\t", "\u25A0\t"]
        ]
        
        #boss room symbol
        map[0][0] = "\u2620\t"
        #setting player symbol at the proper coordinates
        map[self.row_pos][self.col_pos] = "\u25CB\t"
    
        print("\n----Map Of The Dungeon----")
        for row in map:
            for item in row:
                print(item, end= " ")
            print("\n")
           
            
    def boss_access_attempt(self):
        """
        helper function to see if player can enter the boss room. This is
        based on if the player has the note in their inventory
        Returns:
            let_in (bool) true if player is allowed access, false otherwise
        
        """
        print("You stand upon a massive door. A plaque says "
                "'Ye who dare enter must speak the words of Ragnaric.'")

        let_in = True if "Mysterious Note" in list(self.inventory.keys()) \
                else False
        
        if let_in:
            
            print("As you speak the words on the note, the mighty door " 
                f"swings open. You are in {data.rooms[0,0]}")
            
        else:
            print("You do not know what to do... Perhaps you can find this "
            "information somehwere.")
        return let_in
        

    def move(self):
        """
        function that allows player to move to a different room
        Side_Effects:
            updates the players row and col attributes if valid move is made.
            prints detailed information about move, such as if it is not allowed
            or what room was entered.
        """
    
        move_accepted = False
        
        while (not move_accepted):
            
            move_direction = input("Choose a direction to move in (w,a,s,d): ")
            
            if move_direction.lower() not in ["w", "a", "s", "d"]:
                print("Invalid direction!")
            
            
            #FORWARD
            if move_direction == "w":
                #If at top wall already, cannot move forwards
                if (self.row_pos == 0):
        
                    print("you slam your face into a wall... "
                        "it seems this is as far forward as you can go.")
                    
                #Attempt to enter boss room    
                elif (self.row_pos == 1 and self.col_pos == 0):
                    
                    answer = self.boss_access_attempt()
                    
                    if answer == True:
                        self.row_pos -= 1
                        move_accepted = True
                        
                    else: 
                        continue
                    
                #Valid move
                else:
                    self.row_pos -= 1
                    print("You walk forwards through a door and find "
                        f"yourself in the {data.rooms[(self.row_pos, self.col_pos)]}")
                    move_accepted = True
                    
                    
            #LEFT     
            if move_direction == "a":
                #If at the left wall already, you cannot progress
                if (self.col_pos == 0):
                    
                    print("you slam your face into a wall... "
                        "it seems this is as far left as you can go.")
                
                #Attempt to enter boss room
                elif (self.row_pos == 0 and self.col_pos == 1):
                    
                    answer = self.boss_access_attempt()
                    
                    if answer == True:
                        self.col_pos -= 1
                        move_accepted = True
                        
                    else:
                        continue
                    
                #Valid move
                else:
                    self.col_pos -= 1
                    print("You walk to your left through a door and find "
                        f"yourself in the {data.rooms[(self.row_pos, self.col_pos)]}")
                    move_accepted = True
            #DOWN
            if move_direction == "s":
                #Barrier of map
                if (self.row_pos == 3):
                    
                    print("you slam your face into a wall... "
                        "it seems this is as far backwards as you can go.")
                #Valid move
                else:
                    self.row_pos += 1
                    print("You walk backwards through a door and find "
                        f"yourself in the {data.rooms[(self.row_pos, self.col_pos)]}")
                    move_accepted = True
            #RIGHT
            if move_direction == "d":
                #Barrier of map
                if (self.col_pos == 3):
                    
                    print("you slam your face into a wall... "
                        "it seems this is as far right as you can go.")
                #Valid move
                else:
                    self.col_pos += 1
                    print("You walk to your right through a door and find "
                        f"yourself in the {data.rooms[(self.row_pos, self.col_pos)]}")
                    move_accepted = True
                    
        clear_terminal()        


    def light_attack(self, enemy):
        """
        function for the player to preform a light attack
        Args:
            enemy (Enemy) the enemy being attacked
        Side Effects:
            prints flavor text during the attacks
            updates the enemy health to cause damage
        """
        
        total_miss_chance = self.weapon.light_miss_chance + enemy.dodge_chance
        #successful hit
        if random.randint(0,100) > total_miss_chance:
            if self.character_class == "Warrior":
                print(f"You quickly jab your Battleaxe into the side of the " 
                    f"{enemy.name}, dealing {self.weapon.light_damage} damage.")
                
            if self.character_class == "Mage":
                print(f"You swiftly raise your Grand Staff, and launch a bolt "
                    "of light at the " 
                    f"{enemy.name}, dealing {self.weapon.light_damage} damage.")
            
            if self.character_class == "Thief":
                print(f"You quickly slash the {enemy.name} with your Obsidian "
                    f"Dagger, dealing {self.weapon.light_damage} damage.")
                    
            enemy.health -= self.weapon.light_damage
            print(f"The {enemy.name} has {enemy.health if enemy.health > 0 else 0}" 
                " health remaining.")
        else:
            print(f"The {enemy.name} dodges the attack!")
        
                
    def heavy_attack(self, enemy):
        """
        function that allows player to perform a heavy attack
        Args:
            enemy (Enemy) the enemy being attacked
        Side Effects:
            Prints flavor text for the attack
            updates enemy health
        """
        total_miss_chance = self.weapon.heavy_miss_chance + enemy.dodge_chance
        #successful hit
        if random.randint(0,100) > total_miss_chance:
            if self.character_class == "Warrior":
                print(f"With a echoing roar, you slam your Battleaxe into the " 
                    f"{enemy.name}, dealing {self.weapon.heavy_damage} damage.")
                
            if self.character_class == "Mage":
                print(f"After channeling your energy into your Grand Staff, "
                    "A blue beam erupts from the orb and hurls towards the " 
                    f"{enemy.name}, dealing {self.weapon.heavy_damage} damage.")
            
            if self.character_class == "Thief":
                print(f"You lunge into the {enemy.name} with your Obsidian "
                    f"Dagger, dealing {self.weapon.heavy_damage} damage.")
                    
            enemy.health -= self.weapon.heavy_damage
            print(f"The {enemy.name} has {enemy.health if enemy.health > 0 else 0}" 
                " health remaining.")
        else:
            print(f"The {enemy.name} dodges the attack!")
    
    
    def heal(self):
        """
        Function to allow player to heal
        Side Effects:
            prints flavor text
            updates player health
            updates player potion count
        Returns:
            False if player has no potions to heal with
        """
        if self.inventory["Health Potion"] > 0:
            if self.health + 60 < self.max_health:
                self.health += 60
            else:
                self.health = self.max_health
            self.inventory["Health Potion"] -= 1
                
            print(f"You drink a health potion. your hp is now "
                  f"{self.health}/{self.max_health}")
        else:
            print("You are out of health potions.")


    def remove_item(self):
        """
        Method for removing items from player inventory.
        
        Side Effects:
            Updates players inventory dictionary.
            Prints inventory actions.
        Returns:
            True if item was removed, false otherwise.
        """
        
        if len(self.inventory) == 0:
            print("Inventory is empty. Nothing to remove.")
            return False
        
        print("\n Your Inventory:")
        sorted_items = sorted(self.inventory.items(), key=lambda x:x[1], reverse=True)
        
        # loops through index
        i = 0
        while i < len(sorted_items):
            item, amount = sorted_items[i]
            print(str(i + 1) + ". " + item + " (x" + str(amount) + ")")
            i += 1
            
        choice = input('Choose item to remove or press "q" to cancel: ')   
        if choice == 'q':
            return False
        
        try:
            index = int(choice) - 1
            item_removed = sorted_items[index][0]
        
            self.inventory[item_removed] = self.inventory[item_removed] - 1
        
            if self.inventory[item_removed] == 0:
                del self.inventory[item_removed]
                
            print("You dropped " + item_removed)
            return True
    
        except:
            print("What are you saying?")
            return False
        
        
    def loot_enemy(self, enemy):
        """
        Function to pick up items from slain enemies. 
        
        Args:
            enemy (Enemy): The enemy being looted.
            
        Side Effects:
            Updates the players inventory.
            Calls the remove_item function if player chooses to pick up item
            while their inventory is full.
            Prints inventory.
        """
        max_inv = 5
        
        priority_items = {"Mysterious Note": 3, "Health Potion": 2}
        sorted_loot = sorted(enemy.inventory, 
                            key=lambda x:priority_items.get(x, 1), reverse=True)
        
        print("\nYou search the slain foe...")
        
        for item in sorted_loot:
            
            choice = input("Take " + item + "? (y/n): ")
        
            while choice != 'y' and choice != 'n':
                choice = input("Enter y for Yes or n for No: ")
                
            if choice == 'n':
                print("You leave the " + item)
                continue
            
            print("You grab " + item + "...")

            # if item already in inventory
            if item in self.inventory:
                self.inventory[item] += 1
                print(item + " now x" + str(self.inventory[item]))
                continue
            
            # if inventory NOT full
            if len(self.inventory) < max_inv:
                self.inventory[item] = 1
                print("You picked up " + item)
                continue
            
            # if inventory is full
            print("Inventory full!")
            
            removed = self.remove_item()
            
            if removed == True:
                self.inventory[item] = 1
                print(item + " added")
            else:
                print("You leave the " + item)    
                
        print("\nFinal Inventory:")
        for item_name in self.inventory:
            print(item_name + ": x" + str(self.inventory[item_name]))
           
            
    def __str__(self):
        """
        informal string representation to be called when player checks status
        Returns:
            The status of the player via a detailed string
        
        """
        weapon_name = self.weapon.weapon_name
        print("\n")
        
        if self.health > 99:
            return (f"You are in good shape! \nClass: {self.character_class}\n" 
                f"Health: {self.health}\nWeapon: {weapon_name}")
        
        elif self.health > 80 and self.character_class != "Thief":
            return (f"You are in okay shape! \nClass: {self.character_class}\n" 
            f"Health: {self.health} \nWeapon: {weapon_name}")
        
        elif self.health > 80 and self.character_class == "Thief":
            return (f"You are in good shape! \nClass: {self.character_class}\n" 
            f"Health: {self.health} \nWeapon: {weapon_name}")
        
        elif self.health > 50 and self.character_class == "Thief":
            return (f"You are in okay shape! \nClass: {self.character_class}\n" 
                f"Health: {self.health} \nWeapon: {weapon_name}")
        
        else:
            return (f"You are in bad shape! \nClass: {self.character_class}\n" 
            f"Health: {self.health} \nWeapon: {weapon_name}")

class Enemy(Character):
    """
    Basic Enemy Class. Will be spawned in during combat encounters.
    Attributes:
        gold(int) the amount of gold held, will be given to player upon defeat.
        
        inventory(list) Enemy's inventory to be looted upon defeat.
        
        potion_count(int) How many health potions the enemy has
        
        damage(int) The damage that will be given to the player if the enemy 
        does an attack move
        
        block_chance(int) The enemy's chance to block the players attach. Will
        be raised if the enemy chooses to defend.
        
        name(string) The enemy's name.
    """
    def __init__(self, health):
        super().__init__(health)
        self.gold = random.randint(20, 100)
        
        self.inventory = ["Health Potion"]
        
        self.potion_count = 2
        
        self.damage = random.randint(15,30)
        
        self.dodge_chance = 0
        
        name_generator = random.randint(1,12)
        self.name = data.enemy_types[name_generator]
        
        item1 = random.randint(1,12)
        self.inventory.append(data.items[item1])
        
        item2 = random.randint(1,12)
        self.inventory.append(data.items[item2])

        note_chance = random.randint(1,10)
        if note_chance == 7:
            self.inventory.append("Mysterious Note")
          
                   
class Weapon():
    def __init__(self, weapon_name, heavy_damage, light_damage, 
                heavy_miss_chance, light_miss_chance):
        self.weapon_name = weapon_name
        self.heavy_damage = heavy_damage
        self.light_damage = light_damage
        self.heavy_miss_chance = heavy_miss_chance
        self.light_miss_chance = light_miss_chance


class Aric(Character):
    """
    Final boss class. Designed to have more health than every other enemy as 
    well as one self-revive in the form of a super potion. 
    
    Attributes: 
    
    Health: The health of the character. 
    Max health: The max amount of health this character can have. 
    Name: name of the character. 
    dodge_chance: chance(0-100) to dodge attacks 
    weapon: weapon instance defining attack damage and miss chances 
    potion_count: number of healing potions the character starts with 
    super_potion: number of super potions character starts with. 
    """
    def __init__(self, health):
        super().__init__(health)  
        self.max_health = health
        self.name = "Aric The Almighty"
        self.dodge_chance = 1
        self.weapon = Weapon("Staff of The Final Exception", 40, 15, 30, 10)
        self.potion_count = 3
        self.super_potion = 1
      
        
    def attack(self, player):
        """
        Performs an attack on a player
        
        params: 
            player(Character): The player being attacked by Aric
        
        returns: 
            None 
        
        """
    
        attack_type = random.choice(["Heavy", "Light"])
        
        
        if attack_type == "Heavy":
        #attack hits
            if random.randint(0,100) > player.dodge_chance:
                player.health -= self.weapon.heavy_damage
                print(f"{self.name} batters you with a heavy blow!\n"
                    f"You have {player.health}/{player.max_health} health left!")
                
        elif attack_type == "Light":
            
            if random.randint(50,100) > player.dodge_chance: 
                player.health -= self.weapon.light_damage
                print(f"{self.name} stuns you with a lightning quick jab!\n"
                    f"you have {player.health}/{player.max_health} health left!")
                            
            
    def heal(self):
        """
        Allows aric to heal up to 50 hp without exceeding max health attribute. 
        Only works if boss is alive and has remaining potions. 
        
        returns: 
            None
        
        
        """
        if 0 < self.potion_count and self.health > 0: 
            if self.health + 50 < self.max_health: 
                self.health += 50
                print(f"{self.name} heals themselves! ")
                print(f"{self.name} has {self.health} remaining!")
            elif self.health == self.max_health:
                self.potion_count -= 1
            
        else: 
            print(f"{self.name} can no longer heal!")
        
        
    def defend(self):
        """
        Sets Aric's dodge chance to 33 when he chooses to defend. 
        
        Returns: 
            None
        """
        self.dodge_chance = 33


def clear_terminal():
    print ("\n" * 3)        
                      
def create_player():
    clear_terminal()
    name = input("After days following the ragged map given you "
                 "by a mysterous man in a tavern,\nyou finally find yourself at "
                 "the entrance of a decrepit dungeon.\nWhat is your name? ")
    
    player_class = "0"
    
    while player_class not in ["1", "2", "3"]:
        clear_terminal()
        player_class = input(f"Very well, {name}. What is your background?.\n"
                            "1. A warrior, veteran of the Great War.\n"
                            "2. A mage, graduate of The Arcane Institute.\n"
                            "3. A thief, legend of the underworld\n")
    
    if player_class == "1":
        player = Player(150, "Warrior", name, 10)
        player.weapon = Weapon("Battleaxe", 65, 35, 50, 20)
        
    elif player_class == "2":
        player = Player(125, "Mage", name, 20)
        player.weapon = Weapon("Grand Staff", 50, 25, 30, 10)
    else:
        player = Player(100, "Thief", name, 65)
        player.weapon = Weapon("Obsidian Dagger", 40, 15, 10, 0)
    
    print(f"After a moment of contemplation, {player.player_name} "
          f"the {player.character_class} enters the dungeon.")
    
    return player
    
#Encounter functions here
def combat(player):
    enemy = Enemy(100)
    clear_terminal()
    print(f"You encounter a hostile {enemy.name}!\n")
    
    while player.health > 0 and enemy.health > 0:
        player_move = None
        
        while player_move not in ["1", "2", "3"]:

            player_move = input("\nSelect your move.\n1 to Heavy Attack\n"
                  "2 to Light Attack\n3 to Heal\n")
            
        if player_move == "1":
            print("\n")
            player.heavy_attack(enemy)
        elif player_move == "2":
            print("\n")
            player.light_attack(enemy)
        else:
            print("\n")
            player.heal()

        if enemy.health <= 0:
            player.gold += enemy.gold
            print(f"You have slain the {enemy.name}, and have found "
                  f"{enemy.gold} pieces of gold.")
            print(f"You now have {player.gold} gold pieces.")
            player.loot_enemy(enemy)
            break

        enemy_action = enemy.choose_move(player)
        enemy.dodge_chance = 0

        if enemy_action == "Attack":
            #attack hits
            if random.randint(0,100) > player.dodge_chance:
                player.health -= enemy.damage
                print(f"The {enemy.name} attacks you!\n"
                      f"You have {player.health if player.health > 0 else 0}"
                      f"/{player.max_health} health left!")
            else:
                print(f"You dodge the {enemy.name}'s attack!")
        elif enemy_action == "Heal":
            enemy.health += 30
            enemy.potion_count -= 1
            print(f"The {enemy.name} drinks a healh potion.\n"
                  f"They now have {enemy.health}/100 health")
        else:
            print(enemy_action)
            enemy.dodge_chance = 30
            print("The enemy prepares for your next move.")

    if player.health <= 0:
        #game over. Function to be added here later.
        print("You have been defeated.")
    

def locked_chest(player):
    """
    Function that simulates a locked chest minigame where player must guess a 
    4-digit code.
    
    Args:
        player (Player): The player attempting to unlock chest.
        
    Side effects:
        Prints instructions and feedback for each guess.
        Updates player gold if chest unlocked.
        Updates player inventory with random reward item.
        Calls remove_item if inventory full.
    """
    print("\n You discover a locked chest with a combination lock...")
    print("You try and guess the 4-digit code to unlock it...")
    print("+ means correct number and position.")
    print("~ means correct number, wrong position.")
    print(". means incorrect number.")
        
            
    code = "".join(str(random.randint(0, 9)) for _ in range(4))
    attempts = 5
            
    while attempts > 0:
        guess = input(f"({attempts}) attempts left, try again...")
                
        if len(guess) != 4 or not guess.isdigit():
            print("That won't work...")
            continue
                
        feedback = []
            
        for i in range(4):
            if guess[i] == code[i]:
                feedback.append("+") # correct position
            elif guess[i] in code:
                feedback.append("~") # wrong position, but in code
            else:
                feedback.append(".") # not in code
                
        print("".join(feedback))
            
        if guess == code:
            print("You hear a click and the chest pops open!")
                    
            reward_gold = random.randint(50, 150)
            player.gold += reward_gold
                    
            item_id = random.randint(1, len(data.items))
            reward_item = data.items[item_id]
                    
            print(f"You found {reward_gold} gold and a {reward_item}!")
                    
            if reward_item in player.inventory:
                player.inventory[reward_item] += 1
                print(reward_item + " now x" + str(player.inventory[reward_item]))
                        
            elif len(player.inventory) < 5:
                player.inventory[reward_item] = 1
                print("You picked up " + reward_item)
                        
            else:
                print("Inventory full!")
                                                
                if player.remove_item():
                    player.inventory[reward_item] = 1
                    print(reward_item + " added")
                else:
                    print("You leave the " + reward_item)
            return
                
        attempts -= 1
            
    print(f"You hear a strange noise, the lock has seized...")
    
    
def shopkeeper(player):
    #Almost done. Error when selling items, as the dict size changes during iteration..
    enter_shop = input("You happen upon a small shop with a gnome tending "
          "the stall. The gnome says he is open for business.\n"
          "Do you approach? (y/n) ")
    
    if enter_shop == "y":
        in_shop = True
        
        while in_shop:
            choice = None
            while choice not in ["1", "2", "3"]:
                choice =input("The gnome says: 'Are ye looking to sell or buy?'"
                        "\nPress 1 to Sell\nPress 2 to Buy\nPress 3 to Leave\n")
            
            if choice == "1":
                
                sellable_items = list(data.items.values())
            
                for item, quantity in list(player.inventory.items()):
                    if item in sellable_items:
                        gold = random.randint(20, 60) * quantity
                        print(f"You sold your {quantity} {item} "
                              f"for {gold} gold.")
                        player.gold += gold
                        player.inventory.pop(item)
                        
                print(f"You now have {player.gold} gold coins.")
        
            elif choice == "2":
                still_buying = True
                
                while still_buying:
                    print(f"\nYou have {player.gold} gold pieces to spend.")
                    buy_choice = input("1. Health Potion: 50 gold pieces\n"
                          "2. Upgrade Heavy Attack: 200 gold pieces.\n"
                          "3. Upgrade Light Attack: 120 gold pieces\n"
                          "4. Increase Agility: 200 gold pieces.\n"
                          "5. Exit\n")
                  
                    if buy_choice == "1":
                        if player.gold >= 50:
                            player.inventory["Health Potion"] += 1
                            player.gold -= 50
                            print("You purchase the health potion.")
                        else:
                            print("You cannot afford this!")
                            
                    elif buy_choice == "2":
                        if player.gold >= 200:
                            player.weapon.heavy_damage += 10
                            player.gold -= 200
                            print(f"You upgraded your heavy attack."
                                " It now does "
                                f"{player.weapon.heavy_damage} damage.")
                        else:
                            print("You cannot afford this!")
                            
                    elif buy_choice == "3":
                        if player.gold >= 120:
                            player.weapon.light_damage += 10
                            player.gold -= 120
                            print(f"You upgraded your light attack."
                                " It now does "
                                f"{player.weapon.light_damage} damage.")
                        else:
                            print("You cannot afford this!")
                            
                    elif buy_choice == "4":
                        if player.gold >= 200:
                            player.dodge_chance += 10
                            player.gold -= 200
                            print(f"You upgraded your agility. "
                                f"You now have a {player.dodge_chance}% chance "
                                f"to dodge an incoming attack.")
                        else:
                            print("You cannot afford this!")
                    else:
                        still_buying = False
                        

            else:
                in_shop = False
    
    
    print("You continue on your adventure.")
        
#Cole's totem of luck function. 
def totem_of_luck(player):
    """
    Interactive encounter where the player can choose to gamble with the totem. 

    Args:
        player(Character): Takes the users character 
        
    Returns: 
        None
    
    """
    print("As you enter the room, there is no trace of life. In the center "
              "lies an old stone totem, covered in years of moss.\n"
              "There is a pitch black pit in the totem's open mouth. "
              "Carvings in the stone reads 'Do you feel lucky, Punk?'\n")
        
        
    choice = input(f"{player.player_name} do you wish to interact"
                     " with the totem of luck? (y/n): ")
        
    while choice != 'y' and choice != 'n':
            choice = input("Enter 'y' for Yes or 'n' for No: ").casefold()
                
    if choice == 'n':
        print("You decide that you are not in a gambling mood.")
         
            
        
    if choice == 'y':
        print("After a moment of though, you remember that "
                  "luck favors the bold, and reach into the totem jaws.")

        luck = random.randint(1,2)
        if luck == 1: 
                print("The totem's mouth snaps closed, causing a severe wound")
                player.health = player.health * 30 // 100
                print("You lose %30 of your health.")
                print(f"Current health: {player.health}")
               
            
        if luck == 2:
            print("You reach into the mouth and grab a pouch of gold coins.")
            gold = random.randint(80,200)
            player.gold += gold 
            print(f"Congrats you've earned {gold} gold!")

#logan's riddler            
def riddler(player):
    print("After entering this dark room you freeze. Across from you sits an "
          "old troll\n")
    
    print(f"'Ah {player.player_name} it has been a while.\nAnswer my riddle "
          "correctly only using one word and you will pass.\n"
          "Fail and I will give you a slap.'")
    
    riddles = {("I have four legs in the morning, two in the afternoon, and "
               "three in the evening. What am I? ") : "human",
               ("I have no mouth, but I can still talk. I often repeat, but I "
               "never balk. What am I? "): "echo",
               "What has a spine but no bones?" : "book",
               "I’m full of holes, but I can hold water. What am I? " : "sponge",
               "What gets wet as it dries? " : "towel",
               "What has keys but can't open locks? " : "piano"           
    }
    items = list(riddles.items())
    option = random.randint(0, len(items)-1 )
    question, answer = items[option]
    response = input(question)
    if response.lower() != answer:
        player.health -= 10
        print(f"WRONG! You now have {player.health} health!")
    else:
        print("Correct! You may pass")           
           
                
def free_roam(player):
    ###function that calls other functions
    # Only ends once you leave room
    
    choice_switch = False
    
    while not choice_switch:
        clear_terminal()
        choice = input("You are now in free roam. Choose an action:\n"
                "1: Inspect Map\n"
                "2: Manage Inventory\n"
                "3: Check Status\n"
                "4: Heal\n"
                "5: Leave Room\n")
        if choice == '1':
            player.display_dungeon_map()
            
        elif choice == '2':
            player.remove_item()
        elif choice == "3":
            print(player)

        elif choice == '4':
            player.heal()
            
        elif choice == '5':
            player.move()
            choice_switch = True
        else:
            continue
        
        
def reward(player):
    """
    Reward function that gets called once final boss is defeated. 
    is_hero attibute to True 

    Args:
        player (Character): Takes user's character 
    """
    aric = Aric(100)
    print("Arric the Almighty staggers... ")
    time.sleep(2)
    print("'Impossible'...")
    time.sleep(2)
    print("He falls to one knee...")
    time.sleep(2)
    print("...'Very well.. You pass.'\n")
    time.sleep(2)
    print("---REWARDS---")
    print("-- A passing grade")
    print(f"-- {aric.weapon.weapon_name}")
    time.sleep(1)
    
    print("'One more thing before you go.. '")
    print("")
    player.is_hero = True
    
    
def encounter_manager(player):
    #First, Check if player is in boss room. if so, always call boss fight
    if player.col_pos == 0 and player.row_pos == 0:
        boss_fight(player)
    elif player.combat_streak == False:
        combat(player)
        player.combat_streak = True

    else:
        chance = random.randint(1,100)
        if chance > 40:
            combat(player)
            player.combat_streak = True
        else:
            noncombat = random.randint(0,3)
            if noncombat == 0:
                shopkeeper(player)
            elif noncombat == 1:
                totem_of_luck(player)
            elif noncombat == 2:
                riddler(player)
            else:
                locked_chest(player)
      
            player.combat_streak = False
    
    
def boss_fight(player):
    """
    Function that initiates final boss fight between player and Aric. 

    Args:
        player (Character): Takes user's character 
    """
    aric = Aric(175)
    #Aric's opening monologue vvv
    time.sleep(2)
    print(f"You've made it...")
    time.sleep(2)
    print(f"You think you brought yourself here?")
    time.sleep(2)
    print(f"This dungeon.. Every rule you've followed, every path you've taken,")
    time.sleep(3)
    print("was me.")
    time.sleep(3)
    print(f"Now come. Show me what you've learned.\n")
    print("\n")
    time.sleep(3)
    
    while player.health > 0 and aric.health > 0:
        player_move = None
        
        while player_move not in ["1", "2", "3"]:
            player_move = input("Select your move.\n1 to Heavy Attack\n"
                  "2 to Light Attack\n3 to Heal\n")
            
        if player_move == "1":
            player.heavy_attack(aric)
        elif player_move == "2":
            player.light_attack(aric)
        else:
            player.heal()
        
        
        if aric.health <= 0 and aric.super_potion > 0: 
                aric.health = aric.max_health
                aric.super_potion -= 1
                print(f"{aric.name} resurrects using a Super Potion!")
                
        elif aric.health > 0:
            
            aric_act = aric.choose_move(player)
        
            if aric_act == "Attack":
                aric.attack(player)
                
            if aric_act == "Heal":
                aric.heal()
            
            if aric_act == "Defend":
                aric.defend()
                print(f"Dodge chance = {aric.dodge_chance}")
                aric.dodge_chance = 1
        
        else: 
            reward(player)
            
            break

def victory(player):
    clear_terminal()
    
    print("After slaying the dungeon's ruler, "
          "you triumphantly begin the trek home.\n")
    
    if player.character_class  == "Warrior":
        
        print(f"Congratulations {player.player_name} the {player.character_class}.\n"
              "Yet another foe falls under your mighty axe. The gods will"
               " be pleased.")
    elif player.character_class == "Mage":
        print(f"Congratulations {player.player_name} the {player.character_class}.\n"
              "The Academy will be pleased to gain this knowledge")
    else:
        print(f"Congratulations {player.player_name} the {player.character_class}.\n"
              "Your spoils will fetch a heavy pouch of gold.")
        
    with open("player_final_stats.txt", "w", encoding="utf-8") as file:
        file.write("---- VICTORIOUS CAMPAIGN! ----\n")
        file.write("ENDGAME STATS:\n")
        file.write(f"Character Name: {player.player_name}\n")
        file.write(f"Class: {player.character_class}\n")
        file.write(f"Health: {player.health} / {player.max_health}\n")
        file.write(f"Gold: {player.gold}\n")
        file.write("\nInventory:\n")
        if len(player.inventory) == 0:
            file.write("Empty\n")
        else:
            for item, amount in player.inventory.items():
                file.write(f"{item}: x{amount}\n")
        

def defeat(player):
    clear_terminal()
    
    print("Though you fought valiantly, your might was not enough.\n")
    
    if player.character_class  == "Warrior":
        
        print(f"Your journey ends here {player.player_name} the {player.character_class}.\n"
              "May your soul fight on in Valhalla.")
    elif player.character_class == "Mage":
        print(f"Your journey ends here {player.player_name} the {player.character_class}.\n"
              "Your thirst for knowledge has led to your demise.")
    else:
        print(f"Your journey ends here {player.player_name} the {player.character_class}.\n"
              "Even the quickest hands can't escape fate.")


    


    
if __name__ == "__main__":
    player = create_player()
    
    while player.health > 0 and not player.is_hero:
        
        free_roam(player)
        encounter_manager(player)
    
    if player.is_hero:
        #call victory
        victory(player)
    else:
        #call defeat
        defeat(player)
    